#include "opencodi.h"

enum {
	CMD_MTK_GET_PROTOCOL_VERSION = 0,
	CMD_MTK_GET_CODI_FLASH_VERSION = 1,
	CMD_ST32_INFO_CODI_FLASH_VERSION = 2,
	CMD_ST32_INFO_PROTOCOL_VERSION = 3,
	CMD_ST32_SET_BINARY = 4,
	CMD_ST32_SET_S8 = 5,
	CMD_ST32_RESTART = 6,
	CMD_ST32_GET_DATETIME = 7,
	CMD_MTK_INFO_DATETIME = 8,
	CMD_ST32_SET_LOCATION_STATUS = 9,
	CMD_ST32_GET_LOCATION_STATUS = 10,
	CMD_MTK_INFO_LOCATION_STATUS = 11,
	CMD_ST32_SET_TORCH_STATUS = 12,
	CMD_ST32_GET_TORCH_STATUS = 13,
	CMD_MTK_INFO_TORCH_STATUS = 14,
	CMD_ST32_GET_COVER_STATUS = 15,
	CMD_MTK_INFO_COVER_STATUS = 16,
	CMD_ST32_SET_WIFI_STATUS = 17,
	CMD_ST32_GET_WIFI_STATUS = 18,
	CMD_MTK_INFO_WIFI_STATUS = 19,
	CMD_ST32_SET_BT_STATUS = 20,
	CMD_ST32_GET_BT_STATUS = 21,
	CMD_MTK_INFO_BT_STATUS = 22,
	CMD_ST32_SET_BATTERY_SAVER_STATUS = 23,
	CMD_ST32_GET_BATTERY_SAVER_STATUS = 24,
	CMD_MTK_INFO_BATTERY_SAVER_STATUS = 25,
	CMD_ST32_SET_FLIGHT_MODE_STATUS = 26,
	CMD_ST32_GET_FLIGHT_MODE_STATUS = 27,
	CMD_MTK_INFO_FLIGHT_MODE_STATUS = 28,
	CMD_ST32_SET_HOTSPOT_STATUS = 29,
	CMD_ST32_GET_HOTSPOT_STATUS = 30,
	CMD_MTK_INFO_HOTSPOT_STATUS = 31,
	CMD_ST32_SET_MOBILE_DATA_STATUS = 32,
	CMD_ST32_GET_MOBILE_DATA_STATUS = 33,
	CMD_MTK_INFO_MOBILE_DATA_STATUS = 34,
	CMD_ST32_SET_DND_STATUS = 35,
	CMD_ST32_GET_DND_STATUS = 36,
	CMD_MTK_INFO_DND_STATUS = 37,
	CMD_ST32_SET_VOLUME_LEVEL = 38,
	CMD_ST32_GET_VOLUME_LEVEL = 39,
	CMD_MTK_INFO_VOLUME_LEVEL = 40,
	CMD_ST32_GET_BATTERY_LEVEL = 41,
	CMD_MTK_INFO_BATTERY_LEVEL = 42,
	CMD_ST32_INFO_CODI_STATUS = 43,
	CMD_MTK_SET_CODI_STATUS = 44,
	CMD_ST32_SET_LOCK = 45,
	CMD_ST32_GET_LOCK_STATUS = 46,
	CMD_MTK_INFO_LOCK_STATUS = 47,
	CMD_ST32_DISMISS_CALL_SMS = 48,
	CMD_ST32_ACTION_UNLOCK = 49,
	CMD_ST32_INFO_ST_CHARGING = 50,
	CMD_ST32_PLAY_DTMF = 51,
	CMD_ST32_SEND_DTMF = 52,
	CMD_ST32_ACTION_CALL = 53,
	CMD_ST32_SEND_TELE_CODE = 54,
	CMD_ST32_SET_CALL_MUTE_STATUS = 55,
	CMD_ST32_GET_CALL_MUTE_STATUS = 56,
	CMD_MTK_INFO_CALL_MUTE_STATUS = 57,
	CMD_ST32_SET_CALL_OUTPUT = 58,
	CMD_ST32_GET_CALL_OUTPUT = 59,
	CMD_MTK_INFO_CALL_OUTPUT = 60,
	CMD_ST32_GET_CALL_OUTPUT_OPTIONS = 61,
	CMD_MTK_INFO_CALL_OUTPUT_OPTIONS = 62,
	CMD_ST32_ACTION_CAMERA = 63,
	CMD_ST32_GET_CAMERA_FRAME = 64,
	CMD_ST32_SET_CAMERA_SETTINGS = 65,
	CMD_ST32_CAMERA_CAPTURE_IMAGE = 66,
	CMD_ST32_ACTION_VIDEO = 67,
	CMD_ST32_GET_VIDEO_FRAME = 68,
	CMD_ST32_SET_VIDEO_SETTINGS = 69,
	CMD_ST32_VIDEO_CAPTURE_IMAGE = 70,
	CMD_MTK_INFO_CAMERA_STATUS = 71,
	CMD_MTK_INFO_CAMERA_SETTINGS = 72,
	CMD_MTK_INFO_VIDEO_STATUS = 73,
	CMD_MTK_INFO_VIDEO_SETTINGS = 74,
	CMD_MTK_INFO_COVER_LIGHT_SENSOR = 75,
	CMD_ST32_GET_COVER_LIGHT_SENSOR = 76,
	CMD_MTK_LOAD_LANGUAGE_RESOURCE = 77,
	CMD_MTK_GET_CURRENT_LANGUAGE = 78,
	CMD_ST32_INFO_CURRENT_LANGUAGE = 79,
	CMD_MTK_SET_CURRENT_LANGUAGE = 80,
	CMD_MTK_SHOW_MEDIA = 81,
	CMD_MTK_STOP_MEDIA = 82,
	CMD_MTK_LOAD_MEDIA = 83,
	CMD_MTK_UNLOAD_MEDIA = 84,
	CMD_MTK_HAS_MEDIA = 85,
	CMD_ST32_INFO_MEDIA_RESOURCE = 86,
	CMD_ST32_INFO_MEDIA_ACTIVITY = 87,
	CMD_MTK_SHOW_ALERT = 88,
	CMD_ST32_INFO_ALERT = 89,
	CMD_MTK_STOP_ALERT = 90,
	CMD_MTK_ORIENTATION_INFO = 91,
	CMD_ST32_GET_ORIENTATION = 92,
	CMD_MTK_ACTION_CODI_HOME = 93,
	CMD_MTK_INFO_NEXT_ALARM = 94,
	CMD_MTK_SHOW_BATTERY_LEVEL = 95,
	CMD_ST32_GET_CALL_HISTORY = 96,
	CMD_ST32_GET_CONTACTS = 97,
	CMD_MTK_CONTACT_INFO = 98,
	CMD_MTK_CALL_HISTORY_INFO = 99,
	CMD_MTK_NOTIFICATION_INFO = 100,
	CMD_MTK_PLAYER_INFO = 101,
	CMD_ST32_ACTION_PLAYER = 102,
	CMD_MTK_CALL_INFO = 103,
	CMD_ST32_ACTION_NOTIFICATION = 104,
	CMD_ST32_GET_LEDISON_PATTERN = 105,
	CMD_MTK_LEDISON_MODE_INFO = 106,
	CMD_ST32_GET_LEDISON_MODE = 107,
	CMD_MTK_LEDISON_PATTERN_INFO = 108,
	CMD_ST32_GET_CONTACT_ICON = 109,
	CMD_MTK_CONTACT_ICON_INFO = 110,
	CMD_MTK_MODEM_SIGNAL_INFO = 111,
	CMD_MTK_WEATHER_INFO = 112,
	CMD_MTK_EXTRA_COMMAND = 113,
	CMD_ST32_GET_MODEM_SIGNAL_INFO = 114,
	CMD_ST32_GET_DATE_TIME_FORMAT = 115,
	CMD_MTK_DATE_TIME_FORMAT_INFO = 116,
	CMD_ST32_GET_ALBUM_ART = 117,
	CMD_MTK_ALBUM_ART_INFO = 118,
	CMD_MTK_CAMERA_FRAME_IMG = 119,
	CMD_MTK_KEY_PRESS_INFO = 120,
	CMD_ST32_ACTION_VOICE_RECODER = 122,
	CMD_ST32_SET_VOICE_RECORDER_SETTINGS = 123,
	CMD_MTK_INFO_VOICE_RECODER_SETTINGS = 124,
	CMD_MTK_INFO_VOICE_RECORDER_STATUS = 125,
	CMD_MTK_DATA_CHANGE_ALERT = 126,
	CMD_ST32_DATA_CHANGE_ALERT = 127,
	CMD_MTK_APPLICATION_ICON_INFO = 128,
	CMD_ST32_GET_APPLICATION_ICON = 129,
	CMD_ST32_GET_SCREEN_OFF_TIMEOUT = 130,
	CMD_MTK_SCREEN_OFF_TIMEOUT_INFO = 131,
	CMD_AEON_MTK_SET_ST32_RESET = 140,
	CMD_GET_ST32_SW_VERSION = 141,
	CMD_SYNC_USB_STATUS = 142,
	CMD_SYNC_SYS_SLEEP_STATUS = 143,
	CMD_SYNC_RIGHT_USB_OTG_STATUS = 144
};

char *getPacketName(uint32_t id) {
	switch (id) {
		case CMD_MTK_GET_PROTOCOL_VERSION: return "MTK_GET_PROTOCOL_VERSION";
		case CMD_MTK_GET_CODI_FLASH_VERSION: return "MTK_GET_CODI_FLASH_VERSION";
		case CMD_ST32_INFO_CODI_FLASH_VERSION: return "ST32_INFO_CODI_FLASH_VERSION";
		case CMD_ST32_INFO_PROTOCOL_VERSION: return "ST32_INFO_PROTOCOL_VERSION";
		case CMD_ST32_SET_BINARY: return "ST32_SET_BINARY";
		case CMD_ST32_SET_S8: return "ST32_SET_S8";
		case CMD_ST32_RESTART: return "ST32_RESTART";
		case CMD_ST32_GET_DATETIME: return "ST32_GET_DATETIME";
		case CMD_MTK_INFO_DATETIME: return "MTK_INFO_DATETIME";
		case CMD_ST32_SET_LOCATION_STATUS: return "ST32_SET_LOCATION_STATUS";
		case CMD_ST32_GET_LOCATION_STATUS: return "ST32_GET_LOCATION_STATUS";
		case CMD_MTK_INFO_LOCATION_STATUS: return "MTK_INFO_LOCATION_STATUS";
		case CMD_ST32_SET_TORCH_STATUS: return "ST32_SET_TORCH_STATUS";
		case CMD_ST32_GET_TORCH_STATUS: return "ST32_GET_TORCH_STATUS";
		case CMD_MTK_INFO_TORCH_STATUS: return "MTK_INFO_TORCH_STATUS";
		case CMD_ST32_GET_COVER_STATUS: return "ST32_GET_COVER_STATUS";
		case CMD_MTK_INFO_COVER_STATUS: return "MTK_INFO_COVER_STATUS";
		case CMD_ST32_SET_WIFI_STATUS: return "ST32_SET_WIFI_STATUS";
		case CMD_ST32_GET_WIFI_STATUS: return "ST32_GET_WIFI_STATUS";
		case CMD_MTK_INFO_WIFI_STATUS: return "MTK_INFO_WIFI_STATUS";
		case CMD_ST32_SET_BT_STATUS: return "ST32_SET_BT_STATUS";
		case CMD_ST32_GET_BT_STATUS: return "ST32_GET_BT_STATUS";
		case CMD_MTK_INFO_BT_STATUS: return "MTK_INFO_BT_STATUS";
		case CMD_ST32_SET_BATTERY_SAVER_STATUS: return "ST32_SET_BATTERY_SAVER_STATUS";
		case CMD_ST32_GET_BATTERY_SAVER_STATUS: return "ST32_GET_BATTERY_SAVER_STATUS";
		case CMD_MTK_INFO_BATTERY_SAVER_STATUS: return "MTK_INFO_BATTERY_SAVER_STATUS";
		case CMD_ST32_SET_FLIGHT_MODE_STATUS: return "ST32_SET_FLIGHT_MODE_STATUS";
		case CMD_ST32_GET_FLIGHT_MODE_STATUS: return "ST32_GET_FLIGHT_MODE_STATUS";
		case CMD_MTK_INFO_FLIGHT_MODE_STATUS: return "MTK_INFO_FLIGHT_MODE_STATUS";
		case CMD_ST32_SET_HOTSPOT_STATUS: return "ST32_SET_HOTSPOT_STATUS";
		case CMD_ST32_GET_HOTSPOT_STATUS: return "ST32_GET_HOTSPOT_STATUS";
		case CMD_MTK_INFO_HOTSPOT_STATUS: return "MTK_INFO_HOTSPOT_STATUS";
		case CMD_ST32_SET_MOBILE_DATA_STATUS: return "ST32_SET_MOBILE_DATA_STATUS";
		case CMD_ST32_GET_MOBILE_DATA_STATUS: return "ST32_GET_MOBILE_DATA_STATUS";
		case CMD_MTK_INFO_MOBILE_DATA_STATUS: return "MTK_INFO_MOBILE_DATA_STATUS";
		case CMD_ST32_SET_DND_STATUS: return "ST32_SET_DND_STATUS";
		case CMD_ST32_GET_DND_STATUS: return "ST32_GET_DND_STATUS";
		case CMD_MTK_INFO_DND_STATUS: return "MTK_INFO_DND_STATUS";
		case CMD_ST32_SET_VOLUME_LEVEL: return "ST32_SET_VOLUME_LEVEL";
		case CMD_ST32_GET_VOLUME_LEVEL: return "ST32_GET_VOLUME_LEVEL";
		case CMD_MTK_INFO_VOLUME_LEVEL: return "MTK_INFO_VOLUME_LEVEL";
		case CMD_ST32_GET_BATTERY_LEVEL: return "ST32_GET_BATTERY_LEVEL";
		case CMD_MTK_INFO_BATTERY_LEVEL: return "MTK_INFO_BATTERY_LEVEL";
		case CMD_ST32_INFO_CODI_STATUS: return "ST32_INFO_CODI_STATUS";
		case CMD_MTK_SET_CODI_STATUS: return "MTK_SET_CODI_STATUS";
		case CMD_ST32_SET_LOCK: return "ST32_SET_LOCK";
		case CMD_ST32_GET_LOCK_STATUS: return "ST32_GET_LOCK_STATUS";
		case CMD_MTK_INFO_LOCK_STATUS: return "MTK_INFO_LOCK_STATUS";
		case CMD_ST32_DISMISS_CALL_SMS: return "ST32_DISMISS_CALL_SMS";
		case CMD_ST32_ACTION_UNLOCK: return "ST32_ACTION_UNLOCK";
		case CMD_ST32_INFO_ST_CHARGING: return "ST32_INFO_ST_CHARGING";
		case CMD_ST32_PLAY_DTMF: return "ST32_PLAY_DTMF";
		case CMD_ST32_SEND_DTMF: return "ST32_SEND_DTMF";
		case CMD_ST32_ACTION_CALL: return "ST32_ACTION_CALL";
		case CMD_ST32_SEND_TELE_CODE: return "ST32_SEND_TELE_CODE";
		case CMD_ST32_SET_CALL_MUTE_STATUS: return "ST32_SET_CALL_MUTE_STATUS";
		case CMD_ST32_GET_CALL_MUTE_STATUS: return "ST32_GET_CALL_MUTE_STATUS";
		case CMD_MTK_INFO_CALL_MUTE_STATUS: return "MTK_INFO_CALL_MUTE_STATUS";
		case CMD_ST32_SET_CALL_OUTPUT: return "ST32_SET_CALL_OUTPUT";
		case CMD_ST32_GET_CALL_OUTPUT: return "ST32_GET_CALL_OUTPUT";
		case CMD_MTK_INFO_CALL_OUTPUT: return "MTK_INFO_CALL_OUTPUT";
		case CMD_ST32_GET_CALL_OUTPUT_OPTIONS: return "ST32_GET_CALL_OUTPUT_OPTIONS";
		case CMD_MTK_INFO_CALL_OUTPUT_OPTIONS: return "MTK_INFO_CALL_OUTPUT_OPTIONS";
		case CMD_ST32_ACTION_CAMERA: return "ST32_ACTION_CAMERA";
		case CMD_ST32_GET_CAMERA_FRAME: return "ST32_GET_CAMERA_FRAME";
		case CMD_ST32_SET_CAMERA_SETTINGS: return "ST32_SET_CAMERA_SETTINGS";
		case CMD_ST32_CAMERA_CAPTURE_IMAGE: return "ST32_CAMERA_CAPTURE_IMAGE";
		case CMD_ST32_ACTION_VIDEO: return "ST32_ACTION_VIDEO";
		case CMD_ST32_GET_VIDEO_FRAME: return "ST32_GET_VIDEO_FRAME";
		case CMD_ST32_SET_VIDEO_SETTINGS: return "ST32_SET_VIDEO_SETTINGS";
		case CMD_ST32_VIDEO_CAPTURE_IMAGE: return "ST32_VIDEO_CAPTURE_IMAGE";
		case CMD_MTK_INFO_CAMERA_STATUS: return "MTK_INFO_CAMERA_STATUS";
		case CMD_MTK_INFO_CAMERA_SETTINGS: return "MTK_INFO_CAMERA_SETTINGS";
		case CMD_MTK_INFO_VIDEO_STATUS: return "MTK_INFO_VIDEO_STATUS";
		case CMD_MTK_INFO_VIDEO_SETTINGS: return "MTK_INFO_VIDEO_SETTINGS";
		case CMD_MTK_INFO_COVER_LIGHT_SENSOR: return "MTK_INFO_COVER_LIGHT_SENSOR";
		case CMD_ST32_GET_COVER_LIGHT_SENSOR: return "ST32_GET_COVER_LIGHT_SENSOR";
		case CMD_MTK_LOAD_LANGUAGE_RESOURCE: return "MTK_LOAD_LANGUAGE_RESOURCE";
		case CMD_MTK_GET_CURRENT_LANGUAGE: return "MTK_GET_CURRENT_LANGUAGE";
		case CMD_ST32_INFO_CURRENT_LANGUAGE: return "ST32_INFO_CURRENT_LANGUAGE";
		case CMD_MTK_SET_CURRENT_LANGUAGE: return "MTK_SET_CURRENT_LANGUAGE";
		case CMD_MTK_SHOW_MEDIA: return "MTK_SHOW_MEDIA";
		case CMD_MTK_STOP_MEDIA: return "MTK_STOP_MEDIA";
		case CMD_MTK_LOAD_MEDIA: return "MTK_LOAD_MEDIA";
		case CMD_MTK_UNLOAD_MEDIA: return "MTK_UNLOAD_MEDIA";
		case CMD_MTK_HAS_MEDIA: return "MTK_HAS_MEDIA";
		case CMD_ST32_INFO_MEDIA_RESOURCE: return "ST32_INFO_MEDIA_RESOURCE";
		case CMD_ST32_INFO_MEDIA_ACTIVITY: return "ST32_INFO_MEDIA_ACTIVITY";
		case CMD_MTK_SHOW_ALERT: return "MTK_SHOW_ALERT";
		case CMD_ST32_INFO_ALERT: return "ST32_INFO_ALERT";
		case CMD_MTK_STOP_ALERT: return "MTK_STOP_ALERT";
		case CMD_MTK_ORIENTATION_INFO: return "MTK_ORIENTATION_INFO";
		case CMD_ST32_GET_ORIENTATION: return "ST32_GET_ORIENTATION";
		case CMD_MTK_ACTION_CODI_HOME: return "MTK_ACTION_CODI_HOME";
		case CMD_MTK_INFO_NEXT_ALARM: return "MTK_INFO_NEXT_ALARM";
		case CMD_MTK_SHOW_BATTERY_LEVEL: return "MTK_SHOW_BATTERY_LEVEL";
		case CMD_ST32_GET_CALL_HISTORY: return "ST32_GET_CALL_HISTORY";
		case CMD_ST32_GET_CONTACTS: return "ST32_GET_CONTACTS";
		case CMD_MTK_CONTACT_INFO: return "MTK_CONTACT_INFO";
		case CMD_MTK_CALL_HISTORY_INFO: return "MTK_CALL_HISTORY_INFO";
		case CMD_MTK_NOTIFICATION_INFO: return "MTK_NOTIFICATION_INFO";
		case CMD_MTK_PLAYER_INFO: return "MTK_PLAYER_INFO";
		case CMD_ST32_ACTION_PLAYER: return "ST32_ACTION_PLAYER";
		case CMD_MTK_CALL_INFO: return "MTK_CALL_INFO";
		case CMD_ST32_ACTION_NOTIFICATION: return "ST32_ACTION_NOTIFICATION";
		case CMD_ST32_GET_LEDISON_PATTERN: return "ST32_GET_LEDISON_PATTERN";
		case CMD_MTK_LEDISON_MODE_INFO: return "MTK_LEDISON_MODE_INFO";
		case CMD_ST32_GET_LEDISON_MODE: return "ST32_GET_LEDISON_MODE";
		case CMD_MTK_LEDISON_PATTERN_INFO: return "MTK_LEDISON_PATTERN_INFO";
		case CMD_ST32_GET_CONTACT_ICON: return "ST32_GET_CONTACT_ICON";
		case CMD_MTK_CONTACT_ICON_INFO: return "MTK_CONTACT_ICON_INFO";
		case CMD_MTK_MODEM_SIGNAL_INFO: return "MTK_MODEM_SIGNAL_INFO";
		case CMD_MTK_WEATHER_INFO: return "MTK_WEATHER_INFO";
		case CMD_MTK_EXTRA_COMMAND: return "MTK_EXTRA_COMMAND";
		case CMD_ST32_GET_MODEM_SIGNAL_INFO: return "ST32_GET_MODEM_SIGNAL_INFO";
		case CMD_ST32_GET_DATE_TIME_FORMAT: return "ST32_GET_DATE_TIME_FORMAT";
		case CMD_MTK_DATE_TIME_FORMAT_INFO: return "MTK_DATE_TIME_FORMAT_INFO";
		case CMD_ST32_GET_ALBUM_ART: return "ST32_GET_ALBUM_ART";
		case CMD_MTK_ALBUM_ART_INFO: return "MTK_ALBUM_ART_INFO";
		case CMD_MTK_CAMERA_FRAME_IMG: return "MTK_CAMERA_FRAME_IMG";
		case CMD_MTK_KEY_PRESS_INFO: return "MTK_KEY_PRESS_INFO";
		case CMD_ST32_ACTION_VOICE_RECODER: return "ST32_ACTION_VOICE_RECODER";
		case CMD_ST32_SET_VOICE_RECORDER_SETTINGS: return "ST32_SET_VOICE_RECORDER_SETTINGS";
		case CMD_MTK_INFO_VOICE_RECODER_SETTINGS: return "MTK_INFO_VOICE_RECODER_SETTINGS";
		case CMD_MTK_INFO_VOICE_RECORDER_STATUS: return "MTK_INFO_VOICE_RECORDER_STATUS";
		case CMD_MTK_DATA_CHANGE_ALERT: return "MTK_DATA_CHANGE_ALERT";
		case CMD_ST32_DATA_CHANGE_ALERT: return "ST32_DATA_CHANGE_ALERT";
		case CMD_MTK_APPLICATION_ICON_INFO: return "MTK_APPLICATION_ICON_INFO";
		case CMD_ST32_GET_APPLICATION_ICON: return "ST32_GET_APPLICATION_ICON";
		case CMD_ST32_GET_SCREEN_OFF_TIMEOUT: return "ST32_GET_SCREEN_OFF_TIMEOUT";
		case CMD_MTK_SCREEN_OFF_TIMEOUT_INFO: return "MTK_SCREEN_OFF_TIMEOUT_INFO";
		case CMD_AEON_MTK_SET_ST32_RESET: return "AEON_MTK_SET_ST32_RESET";
		case CMD_GET_ST32_SW_VERSION: return "GET_ST32_SW_VERSION";
		case CMD_SYNC_USB_STATUS: return "SYNC_USB_STATUS";
		case CMD_SYNC_SYS_SLEEP_STATUS: return "SYNC_SYS_SLEEP_STATUS";
		case CMD_SYNC_RIGHT_USB_OTG_STATUS: return "SYNC_RIGHT_USB_OTG_STATUS";
	}

	static char failsafe[10];
	sprintf(failsafe, "unk %lu", id);
	return failsafe;
}

void ocPacketParseAndDispatch(uint32_t id, uint32_t sequence, int size) {
	consolePrint("recv packet %s\n", getPacketName(id));

	switch (id) {
		case CMD_MTK_GET_CODI_FLASH_VERSION:
			ocCommsInitPacket(CMD_ST32_INFO_CODI_FLASH_VERSION, sequence);
			ocCommsPutString("OpenCodi");
			ocCommsSendPacket();
			break;
		case CMD_MTK_DATA_CHANGE_ALERT:
		{
			uint32_t a = ocCommsPeek32(0);
			uint32_t b = ocCommsPeek32(4);
			consolePrint("datachange: %lu/%lu\n", a, b);
			if (a == 104) {
				ocCommsInitPacket(CMD_ST32_DATA_CHANGE_ALERT, sequence);
				ocCommsPut32(a);
				ocCommsPut32(b);
				ocCommsSendPacket();
			}
			break;
		}
	}
}
