#include "opencodi.h"

char *getPacketName(uint32_t id) {
	switch (id) {
		case CMD_MTK_GET_PROTOCOL_VERSION: return "MTK_GET_PROTOCOL_VERSION";
		case CMD_MTK_GET_CODI_FLASH_VERSION: return "MTK_GET_CODI_FLASH_VERSION";
		case CMD_ST32_INFO_CODI_FLASH_VERSION: return "ST32_INFO_CODI_FLASH_VERSION";
		case CMD_ST32_INFO_PROTOCOL_VERSION: return "ST32_INFO_PROTOCOL_VERSION";
		case CMD_ST32_SET_BINARY: return "ST32_SET_BINARY";
		case CMD_ST32_SET_S8: return "ST32_SET_S8";
		case CMD_ST32_RESTART: return "ST32_RESTART";
		case CMD_ST32_GET_DATETIME: return "ST32_GET_DATETIME";
		case CMD_MTK_INFO_DATETIME: return "MTK_INFO_DATETIME";
		case CMD_ST32_SET_LOCATION_STATUS: return "ST32_SET_LOCATION_STATUS";
		case CMD_ST32_GET_LOCATION_STATUS: return "ST32_GET_LOCATION_STATUS";
		case CMD_MTK_INFO_LOCATION_STATUS: return "MTK_INFO_LOCATION_STATUS";
		case CMD_ST32_SET_TORCH_STATUS: return "ST32_SET_TORCH_STATUS";
		case CMD_ST32_GET_TORCH_STATUS: return "ST32_GET_TORCH_STATUS";
		case CMD_MTK_INFO_TORCH_STATUS: return "MTK_INFO_TORCH_STATUS";
		case CMD_ST32_GET_COVER_STATUS: return "ST32_GET_COVER_STATUS";
		case CMD_MTK_INFO_COVER_STATUS: return "MTK_INFO_COVER_STATUS";
		case CMD_ST32_SET_WIFI_STATUS: return "ST32_SET_WIFI_STATUS";
		case CMD_ST32_GET_WIFI_STATUS: return "ST32_GET_WIFI_STATUS";
		case CMD_MTK_INFO_WIFI_STATUS: return "MTK_INFO_WIFI_STATUS";
		case CMD_ST32_SET_BT_STATUS: return "ST32_SET_BT_STATUS";
		case CMD_ST32_GET_BT_STATUS: return "ST32_GET_BT_STATUS";
		case CMD_MTK_INFO_BT_STATUS: return "MTK_INFO_BT_STATUS";
		case CMD_ST32_SET_BATTERY_SAVER_STATUS: return "ST32_SET_BATTERY_SAVER_STATUS";
		case CMD_ST32_GET_BATTERY_SAVER_STATUS: return "ST32_GET_BATTERY_SAVER_STATUS";
		case CMD_MTK_INFO_BATTERY_SAVER_STATUS: return "MTK_INFO_BATTERY_SAVER_STATUS";
		case CMD_ST32_SET_FLIGHT_MODE_STATUS: return "ST32_SET_FLIGHT_MODE_STATUS";
		case CMD_ST32_GET_FLIGHT_MODE_STATUS: return "ST32_GET_FLIGHT_MODE_STATUS";
		case CMD_MTK_INFO_FLIGHT_MODE_STATUS: return "MTK_INFO_FLIGHT_MODE_STATUS";
		case CMD_ST32_SET_HOTSPOT_STATUS: return "ST32_SET_HOTSPOT_STATUS";
		case CMD_ST32_GET_HOTSPOT_STATUS: return "ST32_GET_HOTSPOT_STATUS";
		case CMD_MTK_INFO_HOTSPOT_STATUS: return "MTK_INFO_HOTSPOT_STATUS";
		case CMD_ST32_SET_MOBILE_DATA_STATUS: return "ST32_SET_MOBILE_DATA_STATUS";
		case CMD_ST32_GET_MOBILE_DATA_STATUS: return "ST32_GET_MOBILE_DATA_STATUS";
		case CMD_MTK_INFO_MOBILE_DATA_STATUS: return "MTK_INFO_MOBILE_DATA_STATUS";
		case CMD_ST32_SET_DND_STATUS: return "ST32_SET_DND_STATUS";
		case CMD_ST32_GET_DND_STATUS: return "ST32_GET_DND_STATUS";
		case CMD_MTK_INFO_DND_STATUS: return "MTK_INFO_DND_STATUS";
		case CMD_ST32_SET_VOLUME_LEVEL: return "ST32_SET_VOLUME_LEVEL";
		case CMD_ST32_GET_VOLUME_LEVEL: return "ST32_GET_VOLUME_LEVEL";
		case CMD_MTK_INFO_VOLUME_LEVEL: return "MTK_INFO_VOLUME_LEVEL";
		case CMD_ST32_GET_BATTERY_LEVEL: return "ST32_GET_BATTERY_LEVEL";
		case CMD_MTK_INFO_BATTERY_LEVEL: return "MTK_INFO_BATTERY_LEVEL";
		case CMD_ST32_INFO_CODI_STATUS: return "ST32_INFO_CODI_STATUS";
		case CMD_MTK_SET_CODI_STATUS: return "MTK_SET_CODI_STATUS";
		case CMD_ST32_SET_LOCK: return "ST32_SET_LOCK";
		case CMD_ST32_GET_LOCK_STATUS: return "ST32_GET_LOCK_STATUS";
		case CMD_MTK_INFO_LOCK_STATUS: return "MTK_INFO_LOCK_STATUS";
		case CMD_ST32_DISMISS_CALL_SMS: return "ST32_DISMISS_CALL_SMS";
		case CMD_ST32_ACTION_UNLOCK: return "ST32_ACTION_UNLOCK";
		case CMD_ST32_INFO_ST_CHARGING: return "ST32_INFO_ST_CHARGING";
		case CMD_ST32_PLAY_DTMF: return "ST32_PLAY_DTMF";
		case CMD_ST32_SEND_DTMF: return "ST32_SEND_DTMF";
		case CMD_ST32_ACTION_CALL: return "ST32_ACTION_CALL";
		case CMD_ST32_SEND_TELE_CODE: return "ST32_SEND_TELE_CODE";
		case CMD_ST32_SET_CALL_MUTE_STATUS: return "ST32_SET_CALL_MUTE_STATUS";
		case CMD_ST32_GET_CALL_MUTE_STATUS: return "ST32_GET_CALL_MUTE_STATUS";
		case CMD_MTK_INFO_CALL_MUTE_STATUS: return "MTK_INFO_CALL_MUTE_STATUS";
		case CMD_ST32_SET_CALL_OUTPUT: return "ST32_SET_CALL_OUTPUT";
		case CMD_ST32_GET_CALL_OUTPUT: return "ST32_GET_CALL_OUTPUT";
		case CMD_MTK_INFO_CALL_OUTPUT: return "MTK_INFO_CALL_OUTPUT";
		case CMD_ST32_GET_CALL_OUTPUT_OPTIONS: return "ST32_GET_CALL_OUTPUT_OPTIONS";
		case CMD_MTK_INFO_CALL_OUTPUT_OPTIONS: return "MTK_INFO_CALL_OUTPUT_OPTIONS";
		case CMD_ST32_ACTION_CAMERA: return "ST32_ACTION_CAMERA";
		case CMD_ST32_GET_CAMERA_FRAME: return "ST32_GET_CAMERA_FRAME";
		case CMD_ST32_SET_CAMERA_SETTINGS: return "ST32_SET_CAMERA_SETTINGS";
		case CMD_ST32_CAMERA_CAPTURE_IMAGE: return "ST32_CAMERA_CAPTURE_IMAGE";
		case CMD_ST32_ACTION_VIDEO: return "ST32_ACTION_VIDEO";
		case CMD_ST32_GET_VIDEO_FRAME: return "ST32_GET_VIDEO_FRAME";
		case CMD_ST32_SET_VIDEO_SETTINGS: return "ST32_SET_VIDEO_SETTINGS";
		case CMD_ST32_VIDEO_CAPTURE_IMAGE: return "ST32_VIDEO_CAPTURE_IMAGE";
		case CMD_MTK_INFO_CAMERA_STATUS: return "MTK_INFO_CAMERA_STATUS";
		case CMD_MTK_INFO_CAMERA_SETTINGS: return "MTK_INFO_CAMERA_SETTINGS";
		case CMD_MTK_INFO_VIDEO_STATUS: return "MTK_INFO_VIDEO_STATUS";
		case CMD_MTK_INFO_VIDEO_SETTINGS: return "MTK_INFO_VIDEO_SETTINGS";
		case CMD_MTK_INFO_COVER_LIGHT_SENSOR: return "MTK_INFO_COVER_LIGHT_SENSOR";
		case CMD_ST32_GET_COVER_LIGHT_SENSOR: return "ST32_GET_COVER_LIGHT_SENSOR";
		case CMD_MTK_LOAD_LANGUAGE_RESOURCE: return "MTK_LOAD_LANGUAGE_RESOURCE";
		case CMD_MTK_GET_CURRENT_LANGUAGE: return "MTK_GET_CURRENT_LANGUAGE";
		case CMD_ST32_INFO_CURRENT_LANGUAGE: return "ST32_INFO_CURRENT_LANGUAGE";
		case CMD_MTK_SET_CURRENT_LANGUAGE: return "MTK_SET_CURRENT_LANGUAGE";
		case CMD_MTK_SHOW_MEDIA: return "MTK_SHOW_MEDIA";
		case CMD_MTK_STOP_MEDIA: return "MTK_STOP_MEDIA";
		case CMD_MTK_LOAD_MEDIA: return "MTK_LOAD_MEDIA";
		case CMD_MTK_UNLOAD_MEDIA: return "MTK_UNLOAD_MEDIA";
		case CMD_MTK_HAS_MEDIA: return "MTK_HAS_MEDIA";
		case CMD_ST32_INFO_MEDIA_RESOURCE: return "ST32_INFO_MEDIA_RESOURCE";
		case CMD_ST32_INFO_MEDIA_ACTIVITY: return "ST32_INFO_MEDIA_ACTIVITY";
		case CMD_MTK_SHOW_ALERT: return "MTK_SHOW_ALERT";
		case CMD_ST32_INFO_ALERT: return "ST32_INFO_ALERT";
		case CMD_MTK_STOP_ALERT: return "MTK_STOP_ALERT";
		case CMD_MTK_ORIENTATION_INFO: return "MTK_ORIENTATION_INFO";
		case CMD_ST32_GET_ORIENTATION: return "ST32_GET_ORIENTATION";
		case CMD_MTK_ACTION_CODI_HOME: return "MTK_ACTION_CODI_HOME";
		case CMD_MTK_INFO_NEXT_ALARM: return "MTK_INFO_NEXT_ALARM";
		case CMD_MTK_SHOW_BATTERY_LEVEL: return "MTK_SHOW_BATTERY_LEVEL";
		case CMD_ST32_GET_CALL_HISTORY: return "ST32_GET_CALL_HISTORY";
		case CMD_ST32_GET_CONTACTS: return "ST32_GET_CONTACTS";
		case CMD_MTK_CONTACT_INFO: return "MTK_CONTACT_INFO";
		case CMD_MTK_CALL_HISTORY_INFO: return "MTK_CALL_HISTORY_INFO";
		case CMD_MTK_NOTIFICATION_INFO: return "MTK_NOTIFICATION_INFO";
		case CMD_MTK_PLAYER_INFO: return "MTK_PLAYER_INFO";
		case CMD_ST32_ACTION_PLAYER: return "ST32_ACTION_PLAYER";
		case CMD_MTK_CALL_INFO: return "MTK_CALL_INFO";
		case CMD_ST32_ACTION_NOTIFICATION: return "ST32_ACTION_NOTIFICATION";
		case CMD_ST32_GET_LEDISON_PATTERN: return "ST32_GET_LEDISON_PATTERN";
		case CMD_MTK_LEDISON_MODE_INFO: return "MTK_LEDISON_MODE_INFO";
		case CMD_ST32_GET_LEDISON_MODE: return "ST32_GET_LEDISON_MODE";
		case CMD_MTK_LEDISON_PATTERN_INFO: return "MTK_LEDISON_PATTERN_INFO";
		case CMD_ST32_GET_CONTACT_ICON: return "ST32_GET_CONTACT_ICON";
		case CMD_MTK_CONTACT_ICON_INFO: return "MTK_CONTACT_ICON_INFO";
		case CMD_MTK_MODEM_SIGNAL_INFO: return "MTK_MODEM_SIGNAL_INFO";
		case CMD_MTK_WEATHER_INFO: return "MTK_WEATHER_INFO";
		case CMD_MTK_EXTRA_COMMAND: return "MTK_EXTRA_COMMAND";
		case CMD_ST32_GET_MODEM_SIGNAL_INFO: return "ST32_GET_MODEM_SIGNAL_INFO";
		case CMD_ST32_GET_DATE_TIME_FORMAT: return "ST32_GET_DATE_TIME_FORMAT";
		case CMD_MTK_DATE_TIME_FORMAT_INFO: return "MTK_DATE_TIME_FORMAT_INFO";
		case CMD_ST32_GET_ALBUM_ART: return "ST32_GET_ALBUM_ART";
		case CMD_MTK_ALBUM_ART_INFO: return "MTK_ALBUM_ART_INFO";
		case CMD_MTK_CAMERA_FRAME_IMG: return "MTK_CAMERA_FRAME_IMG";
		case CMD_MTK_KEY_PRESS_INFO: return "MTK_KEY_PRESS_INFO";
		case CMD_ST32_ACTION_VOICE_RECODER: return "ST32_ACTION_VOICE_RECODER";
		case CMD_ST32_SET_VOICE_RECORDER_SETTINGS: return "ST32_SET_VOICE_RECORDER_SETTINGS";
		case CMD_MTK_INFO_VOICE_RECODER_SETTINGS: return "MTK_INFO_VOICE_RECODER_SETTINGS";
		case CMD_MTK_INFO_VOICE_RECORDER_STATUS: return "MTK_INFO_VOICE_RECORDER_STATUS";
		case CMD_MTK_DATA_CHANGE_ALERT: return "MTK_DATA_CHANGE_ALERT";
		case CMD_ST32_DATA_CHANGE_ALERT: return "ST32_DATA_CHANGE_ALERT";
		case CMD_MTK_APPLICATION_ICON_INFO: return "MTK_APPLICATION_ICON_INFO";
		case CMD_ST32_GET_APPLICATION_ICON: return "ST32_GET_APPLICATION_ICON";
		case CMD_ST32_GET_SCREEN_OFF_TIMEOUT: return "ST32_GET_SCREEN_OFF_TIMEOUT";
		case CMD_MTK_SCREEN_OFF_TIMEOUT_INFO: return "MTK_SCREEN_OFF_TIMEOUT_INFO";
		case CMD_AEON_MTK_SET_ST32_RESET: return "AEON_MTK_SET_ST32_RESET";
		case CMD_GET_ST32_SW_VERSION: return "GET_ST32_SW_VERSION";
		case CMD_SYNC_USB_STATUS: return "SYNC_USB_STATUS";
		case CMD_SYNC_SYS_SLEEP_STATUS: return "SYNC_SYS_SLEEP_STATUS";
		case CMD_SYNC_RIGHT_USB_OTG_STATUS: return "SYNC_RIGHT_USB_OTG_STATUS";
	}

	static char failsafe[10];
	sprintf(failsafe, "unk %lu", id);
	return failsafe;
}

void ocPacketParseAndDispatch(uint32_t id, uint32_t sequence, int size) {
	consolePrint("recv packet %s\n", getPacketName(id));

	switch (id) {
		case CMD_MTK_GET_CODI_FLASH_VERSION:
			ocCommsInitPacket(CMD_ST32_INFO_CODI_FLASH_VERSION, sequence);
			ocCommsPutString("OpenCodi");
			ocCommsSendPacket();
			break;
		case CMD_MTK_INFO_DATETIME:
		{
			uint32_t day    = ocCommsPeek32(0);
			uint32_t month  = ocCommsPeek32(4);
			uint32_t year   = ocCommsPeek32(8);
			uint32_t hour   = ocCommsPeek32(12);
			uint32_t minute = ocCommsPeek32(16);
			uint32_t second = ocCommsPeek32(20);
			//uint32_t tz     = ocCommsPeek32(24);
			ocSetTime(day, month, year, hour, minute, second);
			break;
		}
		case CMD_MTK_INFO_BATTERY_LEVEL:
		{
			uint16_t v = ocCommsPeek16(0);
			ocUiSetBatteryLevel(v & 0x80, v & 0x7F);
			break;
		}
		case CMD_MTK_DATA_CHANGE_ALERT:
		{
			uint32_t a = ocCommsPeek32(0);
			uint32_t b = ocCommsPeek32(4);
			consolePrint("datachange: %lu/%lu\n", a, b);
			if (a == 104) {
				ocCommsInitPacket(CMD_ST32_DATA_CHANGE_ALERT, sequence);
				ocCommsPut32(a);
				ocCommsPut32(b);
				ocCommsSendPacket();
			}
			break;
		}
	}
}
